Frontend part of commit
cloudtrack/snu_class_2021_art pull request #17
Opened 2021-12-31 11:36 UTC by 3lna7

I have done some work on frontend regarding the comment section.

I am not sure how to save the comments in the DB plus to later show them for each specific artwork post.

I think I should handle it in the handleComment() function but It will be great to get some hints on that. Maybe if there are similar actions already done in another part of the app that is similar to handling the comment part.

I will be waiting to hear your feedback.

Thank you.

2021-12-31 12:21 UTC, matchy233 requested changes
I made some comments for the things I suggest you to change.

As for binding to backend, there's currently no well-wrapped backend API for you to use directly. You can implement a fake `CommentStore` first with an array of `Comment`s. You can imitate the other stores and design your desired APIs for adding / modifying / deleting ... etc comments entirely in the frontend.

If you want to handle the backend things yourself, you can refer to the code of `AssignmentStore` or `ArtworkStore` and also read the docs of `Amplify` `DataStore` to find examples.

2021-12-31 12:21 UTC, matchy233 commented on src/components/FeedItem/index.tsx
> +  const [commented, setCommented] = useState<string>('');
`liked` and `clicked` are states that can be represetned by a `boolean` value. The `commented` you used here, however, is a `String`. I advise you to use more meaningful name like `userComment` or `commentString` (or maybe just `comment`)

2021-12-31 12:21 UTC, matchy233 commented on src/components/FeedItem/index.tsx
> +                  () => { setClicked(!clicked); }
Using `<IonButton>` to wrap the comment icon will make the ❤ and comment bubble not aligned. It looks pretty annoying to me 😕 better make them aligned

2021-12-31 12:21 UTC, matchy233 commented on src/components/FeedItem/index.tsx
> +          }
This segment is wrapped inside an `<IonGrid>`, it is better to wrap it in `<IonRow>` and / or `<IonCol>` so that we can make the children of `<IonGrid>` better aligned. I suggest you to read the [document of IonGrid](https://ionicframework.com/docs/api/grid).

2022-01-01 08:18 UTC, 3lna7 commented
Sorry, this push is a real mess up. You may want to just look at the implement the backend for comment commit. It had a conflict with my branch so the second commit is to resolve that.

Regarding the frontend issues, I resolved the all review changes you asked for.

But regarding the backend, before you try to test it on your device. I tried to follow the other stores which I was not sure I quite understood well but after I did all changes including commentStore everything worked fine I mean there was not any error and I could see "addComment" print in the consoleLog after pressing the comment button.

I was not sure if I am totally on the wrong path or slightly on the right path but I was not getting any errors so I thought maybe not that wrong.

But Later I don't know for what reason It totally crashed with no errors. I mean right now I cannot make the app function on my computer even when I run ionic serve on my backup files which have no changes. I don't know if this is a cache problem or what. So I could not go more on testing the backend implementation as the feedPage does not show anything in my local right now.

By crashed I mean I cannot see the posts in my feedPage anymore.

If you don't have time to check what is the problem because It looks really messed up so if it is okay I will make a new branch to just push the resolved frontend part at least.

2022-01-01 09:10 UTC, 3lna7 commented
All of a sudden I could see the feedPage again. the commit "Feed page again visible"
So now If you can check and let me know if the way I did it makes sense or should I take an easier path.
I mean time is limiting but I am willing to work more on it if I am even close to something.
Or maybe you can tell me about that fake CommentStore, I am not sure how to do that way.

2022-01-01 11:27 UTC, matchy233 requested changes
I think your backend can work after some modifications but you haven't bind it to the frontend yet. I made some more detailed comments inside.

There are two general issues to notice also. 

1. Please remember to format your code every so often. If you have installed some proper formatter,  the hotkey is `Alt` + `Shift` + `F`. It will make your code much more readable.
2. Write a clear commit message. Your can refer to my other commits as a reference.

2022-01-01 11:27 UTC, matchy233 commented on src/stores/CommentStore.tsx
> +            if (this.rootStore.commentStore.comments.length > 0) {
`RootStore` serves only two functions:

1. Provide a unified outlet for all the stores 
2. Make the contents in other stores available to current store
 
Accessing yourself (`commentStore`) inside a `CommentStore` does not make much sense to me.

2022-01-01 11:27 UTC, matchy233 commented on src/stores/CommentStore.tsx
> +              const assn = new Comment({
I don't thinking naming a `Comment` as `assn` (shorthand for "**assignment**" is a good idea.

2022-01-01 11:27 UTC, matchy233 commented on src/stores/CommentStore.tsx
> +              this.rootStore.classStore.classes.length > 0) {
This is basically the trigger condition for updating `commentStore`. I see in your later implementation that `commentStore` is dependent on `artworkStore`, yet the trigger condition is about `classStore` and `userStore`, which is kind of confusing.

2022-01-01 11:27 UTC, matchy233 commented on src/components/FeedItem/index.tsx
> +          <CommentItem key={artwork.id} username={useranme} avatar={imgURL} comment={"It is a comment"}  />
You are still hard-coding comment here. Idealy we should be able to display comment dynamically like what we're doing now for classes and assignments. My practice is to ``map` the `Class` and `Assignment` in `ClassStore` and `AssignmentStore` respectively. I think you can also do so this way.

2022-01-01 11:27 UTC, matchy233 commented on src/components/FeedItem/index.tsx
> +                <IonButton fill='clear' className="like" onClick={
This is more of a design preference. I think making the comment region taking only the bottom right part of the card is kind of strange. It's hard to only describing using words, but I'd prefer to have both the icons in a row, aligned to the right; and by clicingthe commment bubble the second row will expand to be the comment region.

2022-01-01 11:27 UTC, matchy233 commented on src/stores/CommentStore.tsx
> +              await DataStore.save(assn);
Not a specific issue here, but your `await` usually lacks error handling. It is always good to do `try {...} catch (e) { ... }` or `.then().catch().finally()` to handle possible errors + print extra messages.

2022-01-01 23:57 UTC, 3lna7 commented
So I tried the like part and I think the logic is making sense if you check the 'console.logs'. If we get to do the same I did to 'likes' array to 'artwork.likedUsers' array we can maybe get the likes to stay after page refresh as well. I think artwork.likedUsers array was made for like purpose am I right? If so I think we need to make a copy of the array to be able to extend it with variables which I did not really know how to do this part right. I got it is possible by the mapping but if you could help regarding this would be great. if you have time ofcourse.
I tried to add the commentCount as well,  right now both like and commentCount will disappear after browser refresh but they will stay by changing tabs to class or profile.
One more thing I noticed after clicking on the comment icon, clicking again on it looks a bit weird, I am not sure I did something to it or it was like this by the last changes. Maybe if you could please check that before testing my new code.
Thank you ^^

2022-01-02 00:00 UTC, 3lna7 commented on src/components/FeedItem/index.tsx
> +                <IonButton fill='clear' className="like" onClick={
I do agree too. I will try on it after we get done with the implementation part hopefully.

2022-01-02 11:31 UTC, matchy233 approved these changes
I'll merge this into the main branch now.

2022-01-02 11:32 UTC, merged